### ISSUE TITLE
Dot files indentation

### ISSUE THREAD

**Issue by ad0** [fredokun/arbogen#11]
Is it worth doing indentation in dot files ?
It causes performance issue : 
for example, with examples/binary100000.spec settings and seed=4242,
it takes 14 seconds on my machine to generate and export the tree to non-indented dot file, vs. almost 3 minutes with indentation.

**Comment by Kerl13** [comment]
This is fixed by cf481770639458b93d4a588b6ef5be1ae0bed0ef on master.

String buffering was not enough: the implementation prior to cf481770639458b93d4a588b6ef5be1ae0bed0ef relied on a quadratic function called at each line of the output. The new implementation is of linear amortised cost.

Indented output is still a bit slower but this is fatal since it has to input significantly more text.
The new implementation takes about 3 seconds with indentation on the same example.
